import type {
  Hospital,
  HospitalStats,
  Staff,
  EmergencyCase,
  Department,
  Resource,
  EmergencyCaseWeekly,
  PatientDistribution,
  ResourceDistribution,
  HospitalSurveillanceUploadRecord,
  PublicSurveillanceWeeklyTrend,
  PublicSurveillanceDistrictStat,
  PublicSurveillanceOutbreakAlert,
} from '@/types/hospital';

// Mock Hospital
export const MOCK_HOSPITAL: Hospital = {
  id: 1,
  name: 'City General Hospital',
  address: '123 Healthcare Ave, Medical District',
  phone: '+1 (555) 123-4567',
  email: 'admin@citygeneralhospital.org',
  totalBeds: 284,
  availableBeds: 62,
  totalDoctors: 48,
  totalStaff: 156,
  emergencyCapacity: 50,
  createdAt: '2020-01-15T00:00:00Z',
  updatedAt: new Date().toISOString(),
};

// Mock Hospital Stats (matching sketch: 284, 48, 12, 8min)
export const MOCK_HOSPITAL_STATS: HospitalStats = {
  admittedPatients: 284,
  availableDoctors: 48,
  emergencyCases: 12,
  avgResponseTime: '8 min',
};

// Mock Emergency Cases (12 cases)
export const MOCK_EMERGENCY_CASES: EmergencyCase[] = [
  {
    id: 1,
    patientId: 'P-2024-001',
    patientName: 'John Anderson',
    condition: 'Cardiac Arrest',
    severity: 'critical',
    admittedTime: new Date(Date.now() - 15 * 60 * 1000).toISOString(), // 15 min ago
    status: 'in-treatment',
    assignedDoctor: 'Dr. Sarah Mitchell',
  },
  {
    id: 2,
    patientId: 'P-2024-002',
    patientName: 'Maria Garcia',
    condition: 'Severe Trauma',
    severity: 'critical',
    admittedTime: new Date(Date.now() - 45 * 60 * 1000).toISOString(), // 45 min ago
    status: 'stable',
    assignedDoctor: 'Dr. Michael Chen',
  },
  {
    id: 3,
    patientId: 'P-2024-003',
    patientName: 'Robert Johnson',
    condition: 'Stroke Symptoms',
    severity: 'high',
    admittedTime: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(), // 2 hours ago
    status: 'stable',
    assignedDoctor: 'Dr. Emily Parker',
  },
  {
    id: 4,
    patientId: 'P-2024-004',
    patientName: 'Lisa Thompson',
    condition: 'Severe Allergic Reaction',
    severity: 'high',
    admittedTime: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    status: 'waiting',
    assignedDoctor: 'Dr. James Wilson',
  },
  {
    id: 5,
    patientId: 'P-2024-005',
    patientName: 'David Martinez',
    condition: 'Respiratory Distress',
    severity: 'high',
    admittedTime: new Date(Date.now() - 90 * 60 * 1000).toISOString(),
    status: 'in-treatment',
    assignedDoctor: 'Dr. Sarah Mitchell',
  },
  {
    id: 6,
    patientId: 'P-2024-006',
    patientName: 'Jennifer Lee',
    condition: 'Head Injury',
    severity: 'medium',
    admittedTime: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    status: 'stable',
    assignedDoctor: 'Dr. Michael Chen',
  },
  {
    id: 7,
    patientId: 'P-2024-007',
    patientName: 'William Brown',
    condition: 'Chest Pain',
    severity: 'medium',
    admittedTime: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    status: 'discharged',
    assignedDoctor: 'Dr. Emily Parker',
  },
  {
    id: 8,
    patientId: 'P-2024-008',
    patientName: 'Sarah Davis',
    condition: 'Fracture',
    severity: 'medium',
    admittedTime: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    status: 'waiting',
    assignedDoctor: 'Dr. James Wilson',
  },
  {
    id: 9,
    patientId: 'P-2024-009',
    patientName: 'Michael Wilson',
    condition: 'Abdominal Pain',
    severity: 'low',
    admittedTime: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
    status: 'stable',
    assignedDoctor: 'Dr. Sarah Mitchell',
  },
  {
    id: 10,
    patientId: 'P-2024-010',
    patientName: 'Emily Taylor',
    condition: 'Minor Burns',
    severity: 'low',
    admittedTime: new Date(Date.now() - 7 * 60 * 60 * 1000).toISOString(),
    status: 'discharged',
    assignedDoctor: 'Dr. Michael Chen',
  },
  {
    id: 11,
    patientId: 'P-2024-011',
    patientName: 'Christopher Moore',
    condition: 'Dehydration',
    severity: 'low',
    admittedTime: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    status: 'stable',
    assignedDoctor: 'Dr. Emily Parker',
  },
  {
    id: 12,
    patientId: 'P-2024-012',
    patientName: 'Jessica White',
    condition: 'Migraine',
    severity: 'low',
    admittedTime: new Date(Date.now() - 9 * 60 * 60 * 1000).toISOString(),
    status: 'discharged',
    assignedDoctor: 'Dr. James Wilson',
  },
];

// Mock Weekly Emergency Data (for bar chart)
export const MOCK_WEEKLY_EMERGENCY_DATA: EmergencyCaseWeekly[] = [
  { day: 'Mon', cases: 15 },
  { day: 'Tue', cases: 23 },
  { day: 'Wed', cases: 18 },
  { day: 'Thu', cases: 28 },
  { day: 'Fri', cases: 21 },
  { day: 'Sat', cases: 25 },
  { day: 'Sun', cases: 19 },
];

// Mock Patient Distribution (for pie chart)
export const MOCK_PATIENT_DISTRIBUTION: PatientDistribution[] = [
  { department: 'Emergency', count: 85, percentage: 30, color: '#ef4444' },
  { department: 'Cardiology', count: 62, percentage: 22, color: '#3b82f6' },
  { department: 'Neurology', count: 45, percentage: 16, color: '#8b5cf6' },
  { department: 'Orthopedics', count: 50, percentage: 17, color: '#10b981' },
  { department: 'General', count: 42, percentage: 15, color: '#f59e0b' },
];

// Mock Staff (15 staff members for table)
export const MOCK_STAFF: Staff[] = [
  {
    id: 1,
    name: 'Dr. Sarah Mitchell',
    age: 42,
    gender: 'Female',
    specialization: 'Cardiology',
    department: 'Cardiology',
    email: 's.mitchell@hospital.org',
    phone: '+1 (555) 234-5678',
    patientCount: 18,
    status: 'active',
    joinedDate: '2015-03-20',
  },
  {
    id: 2,
    name: 'Dr. Michael Chen',
    age: 38,
    gender: 'Male',
    specialization: 'Emergency Medicine',
    department: 'Emergency',
    email: 'm.chen@hospital.org',
    phone: '+1 (555) 345-6789',
    patientCount: 22,
    status: 'active',
    joinedDate: '2017-08-15',
  },
  {
    id: 3,
    name: 'Dr. Emily Parker',
    age: 35,
    gender: 'Female',
    specialization: 'Neurology',
    department: 'Neurology',
    email: 'e.parker@hospital.org',
    phone: '+1 (555) 456-7890',
    patientCount: 15,
    status: 'active',
    joinedDate: '2018-01-10',
  },
  {
    id: 4,
    name: 'Dr. James Wilson',
    age: 45,
    gender: 'Male',
    specialization: 'Orthopedics',
    department: 'Orthopedics',
    email: 'j.wilson@hospital.org',
    phone: '+1 (555) 567-8901',
    patientCount: 20,
    status: 'active',
    joinedDate: '2014-06-05',
  },
  {
    id: 5,
    name: 'Dr. Rachel Adams',
    age: 40,
    gender: 'Female',
    specialization: 'Pediatrics',
    department: 'Pediatrics',
    email: 'r.adams@hospital.org',
    phone: '+1 (555) 678-9012',
    patientCount: 25,
    status: 'on-leave',
    joinedDate: '2016-02-28',
  },
  {
    id: 6,
    name: 'Dr. Kevin Patel',
    age: 33,
    gender: 'Male',
    specialization: 'Surgery',
    department: 'Surgery',
    email: 'k.patel@hospital.org',
    phone: '+1 (555) 789-0123',
    patientCount: 12,
    status: 'active',
    joinedDate: '2019-11-12',
  },
  {
    id: 7,
    name: 'Nurse Amy Johnson',
    age: 29,
    gender: 'Female',
    specialization: 'Critical Care Nursing',
    department: 'Emergency',
    email: 'a.johnson@hospital.org',
    phone: '+1 (555) 890-1234',
    patientCount: 30,
    status: 'active',
    joinedDate: '2020-04-18',
  },
  {
    id: 8,
    name: 'Dr. Daniel Kim',
    age: 37,
    gender: 'Male',
    specialization: 'Radiology',
    department: 'Radiology',
    email: 'd.kim@hospital.org',
    phone: '+1 (555) 901-2345',
    patientCount: 8,
    status: 'active',
    joinedDate: '2017-09-22',
  },
  {
    id: 9,
    name: 'Dr. Linda Rodriguez',
    age: 44,
    gender: 'Female',
    specialization: 'Oncology',
    department: 'Oncology',
    email: 'l.rodriguez@hospital.org',
    phone: '+1 (555) 012-3456',
    patientCount: 16,
    status: 'active',
    joinedDate: '2015-07-14',
  },
  {
    id: 10,
    name: 'Dr. Thomas Lee',
    age: 41,
    gender: 'Male',
    specialization: 'Gastroenterology',
    department: 'Gastroenterology',
    email: 't.lee@hospital.org',
    phone: '+1 (555) 123-4567',
    patientCount: 14,
    status: 'unavailable',
    joinedDate: '2016-05-30',
  },
  {
    id: 11,
    name: 'Nurse Maria Santos',
    age: 31,
    gender: 'Female',
    specialization: 'Emergency Nursing',
    department: 'Emergency',
    email: 'm.santos@hospital.org',
    phone: '+1 (555) 234-5678',
    patientCount: 28,
    status: 'active',
    joinedDate: '2019-03-07',
  },
  {
    id: 12,
    name: 'Dr. Robert Taylor',
    age: 50,
    gender: 'Male',
    specialization: 'Cardiology',
    department: 'Cardiology',
    email: 'r.taylor@hospital.org',
    phone: '+1 (555) 345-6789',
    patientCount: 19,
    status: 'active',
    joinedDate: '2012-10-25',
  },
  {
    id: 13,
    name: 'Dr. Anna Martinez',
    age: 36,
    gender: 'Female',
    specialization: 'Dermatology',
    department: 'Dermatology',
    email: 'a.martinez@hospital.org',
    phone: '+1 (555) 456-7890',
    patientCount: 11,
    status: 'active',
    joinedDate: '2018-12-01',
  },
  {
    id: 14,
    name: 'Nurse John Davis',
    age: 27,
    gender: 'Male',
    specialization: 'Surgical Nursing',
    department: 'Surgery',
    email: 'j.davis@hospital.org',
    phone: '+1 (555) 567-8901',
    patientCount: 24,
    status: 'active',
    joinedDate: '2021-01-15',
  },
  {
    id: 15,
    name: 'Dr. Susan White',
    age: 39,
    gender: 'Female',
    specialization: 'Psychiatry',
    department: 'Psychiatry',
    email: 's.white@hospital.org',
    phone: '+1 (555) 678-9012',
    patientCount: 13,
    status: 'active',
    joinedDate: '2017-06-20',
  },
];

// Mock Departments
export const MOCK_DEPARTMENTS: Department[] = [
  {
    id: 1,
    name: 'Emergency',
    totalBeds: 50,
    occupiedBeds: 38,
    availableBeds: 12,
    headDoctor: 'Dr. Michael Chen',
    status: 'normal',
  },
  {
    id: 2,
    name: 'Cardiology',
    totalBeds: 40,
    occupiedBeds: 35,
    availableBeds: 5,
    headDoctor: 'Dr. Sarah Mitchell',
    status: 'critical',
  },
  {
    id: 3,
    name: 'Neurology',
    totalBeds: 30,
    occupiedBeds: 22,
    availableBeds: 8,
    headDoctor: 'Dr. Emily Parker',
    status: 'normal',
  },
  {
    id: 4,
    name: 'Orthopedics',
    totalBeds: 35,
    occupiedBeds: 28,
    availableBeds: 7,
    headDoctor: 'Dr. James Wilson',
    status: 'low',
  },
  {
    id: 5,
    name: 'Pediatrics',
    totalBeds: 45,
    occupiedBeds: 30,
    availableBeds: 15,
    headDoctor: 'Dr. Rachel Adams',
    status: 'normal',
  },
  {
    id: 6,
    name: 'Surgery',
    totalBeds: 25,
    occupiedBeds: 20,
    availableBeds: 5,
    headDoctor: 'Dr. Kevin Patel',
    status: 'critical',
  },
];

// Mock Resources
export const MOCK_RESOURCES: Resource[] = [
  {
    id: 1,
    type: 'beds',
    name: 'Total Beds',
    total: 284,
    available: 62,
    inUse: 222,
    status: 'low',
  },
  {
    id: 2,
    type: 'oxygen',
    name: 'Oxygen Tanks',
    total: 150,
    available: 45,
    inUse: 105,
    status: 'normal',
  },
  {
    id: 3,
    type: 'equipment',
    name: 'Ventilators',
    total: 50,
    available: 8,
    inUse: 42,
    status: 'critical',
  },
  {
    id: 4,
    type: 'equipment',
    name: 'ECG Machines',
    total: 35,
    available: 12,
    inUse: 23,
    status: 'normal',
  },
  {
    id: 5,
    type: 'supplies',
    name: 'Blood Units (Type O-)',
    total: 200,
    available: 45,
    inUse: 155,
    status: 'low',
  },
  {
    id: 6,
    type: 'supplies',
    name: 'Surgical Kits',
    total: 100,
    available: 35,
    inUse: 65,
    status: 'normal',
  },
  {
    id: 7,
    type: 'equipment',
    name: 'Defibrillators',
    total: 25,
    available: 5,
    inUse: 20,
    status: 'critical',
  },
  {
    id: 8,
    type: 'supplies',
    name: 'PPE Kits',
    total: 500,
    available: 180,
    inUse: 320,
    status: 'normal',
  },
];

// Mock Resource Distribution (A: 20%, B: 35%, C: 5%, D: 40%)
export const MOCK_RESOURCE_DISTRIBUTION: ResourceDistribution[] = [
  { category: 'Category A', value: 57, percentage: 20, color: '#3b82f6' },
  { category: 'Category B', value: 99, percentage: 35, color: '#10b981' },
  { category: 'Category C', value: 14, percentage: 5, color: '#f59e0b' },
  { category: 'Category D', value: 114, percentage: 40, color: '#8b5cf6' },
];

export const MOCK_HOSPITAL_SURVEILLANCE_UPLOADS: HospitalSurveillanceUploadRecord[] = [
  {
    id: 'SUR-001',
    hospitalId: 'HSP-001',
    weekStart: '2026-01-05',
    weekEnd: '2026-01-11',
    district: 'Kolkata',
    state: 'West Bengal',
    disease: 'Dengue',
    suspectedCases: 42,
    confirmedCases: 18,
    ageGroup0to17: 11,
    ageGroup18to49: 21,
    ageGroup50Plus: 10,
    maleCases: 24,
    femaleCases: 17,
    otherGenderCases: 1,
    notes: 'Localized rise near ward 8.',
    csvFileName: 'weekly_dengue_jan_w2.csv',
    submittedAt: '2026-01-12T09:15:00Z',
  },
  {
    id: 'SUR-002',
    hospitalId: 'HSP-001',
    weekStart: '2026-01-12',
    weekEnd: '2026-01-18',
    district: 'Kolkata',
    state: 'West Bengal',
    disease: 'Influenza',
    suspectedCases: 57,
    confirmedCases: 26,
    ageGroup0to17: 19,
    ageGroup18to49: 27,
    ageGroup50Plus: 11,
    maleCases: 29,
    femaleCases: 27,
    otherGenderCases: 1,
    notes: 'School cluster observed in south zone.',
    csvFileName: 'influenza_week3.csv',
    submittedAt: '2026-01-19T10:20:00Z',
  },
  {
    id: 'SUR-003',
    hospitalId: 'HSP-002',
    weekStart: '2026-01-12',
    weekEnd: '2026-01-18',
    district: 'Howrah',
    state: 'West Bengal',
    disease: 'Dengue',
    suspectedCases: 31,
    confirmedCases: 14,
    ageGroup0to17: 8,
    ageGroup18to49: 15,
    ageGroup50Plus: 8,
    maleCases: 18,
    femaleCases: 12,
    otherGenderCases: 1,
    notes: 'Cases mostly peri-urban.',
    csvFileName: 'howrah_dengue_week3.csv',
    submittedAt: '2026-01-19T11:45:00Z',
  },
  {
    id: 'SUR-004',
    hospitalId: 'HSP-003',
    weekStart: '2026-01-19',
    weekEnd: '2026-01-25',
    district: 'Durgapur',
    state: 'West Bengal',
    disease: 'Chikungunya',
    suspectedCases: 23,
    confirmedCases: 9,
    ageGroup0to17: 5,
    ageGroup18to49: 13,
    ageGroup50Plus: 5,
    maleCases: 12,
    femaleCases: 10,
    otherGenderCases: 1,
    notes: 'Early containment initiated.',
    csvFileName: 'durgapur_chik_week4.csv',
    submittedAt: '2026-01-26T08:40:00Z',
  },
  {
    id: 'SUR-005',
    hospitalId: 'HSP-001',
    weekStart: '2026-01-26',
    weekEnd: '2026-02-01',
    district: 'Kolkata',
    state: 'West Bengal',
    disease: 'Dengue',
    suspectedCases: 48,
    confirmedCases: 22,
    ageGroup0to17: 10,
    ageGroup18to49: 25,
    ageGroup50Plus: 13,
    maleCases: 26,
    femaleCases: 21,
    otherGenderCases: 1,
    notes: 'Ward 11 and 12 hotspots continue.',
    csvFileName: 'dengue_week5.csv',
    submittedAt: '2026-02-02T09:05:00Z',
  },
];

export const MOCK_SURVEILLANCE_WEEKLY_TRENDS: PublicSurveillanceWeeklyTrend[] = [
  { week: '2026-01-05', disease: 'Dengue', suspectedCases: 73, confirmedCases: 32 },
  { week: '2026-01-12', disease: 'Dengue', suspectedCases: 83, confirmedCases: 38 },
  { week: '2026-01-19', disease: 'Dengue', suspectedCases: 79, confirmedCases: 36 },
  { week: '2026-01-26', disease: 'Dengue', suspectedCases: 88, confirmedCases: 41 },
  { week: '2026-01-05', disease: 'Influenza', suspectedCases: 64, confirmedCases: 24 },
  { week: '2026-01-12', disease: 'Influenza', suspectedCases: 76, confirmedCases: 30 },
  { week: '2026-01-19', disease: 'Influenza', suspectedCases: 69, confirmedCases: 27 },
  { week: '2026-01-26', disease: 'Influenza', suspectedCases: 58, confirmedCases: 21 },
  { week: '2026-01-05', disease: 'Chikungunya', suspectedCases: 28, confirmedCases: 11 },
  { week: '2026-01-12', disease: 'Chikungunya', suspectedCases: 33, confirmedCases: 14 },
  { week: '2026-01-19', disease: 'Chikungunya', suspectedCases: 41, confirmedCases: 17 },
  { week: '2026-01-26', disease: 'Chikungunya', suspectedCases: 37, confirmedCases: 16 },
];

export const MOCK_SURVEILLANCE_DISTRICT_STATS: PublicSurveillanceDistrictStat[] = [
  {
    district: 'Kolkata',
    state: 'West Bengal',
    suspectedCases: 147,
    confirmedCases: 66,
    lastUpdated: '2026-02-02',
  },
  {
    district: 'Howrah',
    state: 'West Bengal',
    suspectedCases: 86,
    confirmedCases: 39,
    lastUpdated: '2026-02-02',
  },
  {
    district: 'Durgapur',
    state: 'West Bengal',
    suspectedCases: 64,
    confirmedCases: 25,
    lastUpdated: '2026-02-02',
  },
  {
    district: 'Siliguri',
    state: 'West Bengal',
    suspectedCases: 52,
    confirmedCases: 19,
    lastUpdated: '2026-02-02',
  },
];

export const MOCK_SURVEILLANCE_OUTBREAK_ALERTS: PublicSurveillanceOutbreakAlert[] = [
  {
    id: 'ALERT-001',
    disease: 'Dengue',
    district: 'Kolkata',
    state: 'West Bengal',
    severity: 'high',
    message: 'Confirmed dengue cases crossed local threshold in 2 contiguous wards.',
    weekStart: '2026-01-26',
  },
  {
    id: 'ALERT-002',
    disease: 'Influenza',
    district: 'Howrah',
    state: 'West Bengal',
    severity: 'medium',
    message: 'School-based influenza cluster is expanding across three institutions.',
    weekStart: '2026-01-19',
  },
  {
    id: 'ALERT-003',
    disease: 'Chikungunya',
    district: 'Durgapur',
    state: 'West Bengal',
    severity: 'low',
    message: 'Steady increase observed but currently under district watch limits.',
    weekStart: '2026-01-19',
  },
];
